# 从面包与原料到线性代数

本 Notebook 通过一个实际的生产计划问题，引入线性代数的核心概念：**线性方程组**、**矩阵-向量乘法**。

**问题目标：** 给定资源总量，求出恰好用完所有资源的生产计划。

## 1. 问题描述

一家公司生产 $n$ 种产品 $N_1, \ldots, N_n$，需要 $m$ 种资源 $R_1, \ldots, R_m$。

- 生产一个单位的产品 $N_j$ 需要 $a_{ij}$ 单位的资源 $R_i$（其中 $i = 1,\ldots,m$，$j = 1,\ldots,n$）。
- 公司共有 $b_i$ 单位的资源 $R_i$ 可用。

**目标：** 找到一个生产计划 $(x_1, \ldots, x_n) \in \mathbb{R}^n$，使得所有资源恰好用完（不多不少）。

### 具体示例：面包店问题

我们有三种产品：
- $N_1$: 面包（Bread）
- $N_2$: 糯米滋（Mochi）
- $N_3$: 蛋黄酥（Egg Yolk Pastry）

我们有三种资源（简化为 3×3 方阵以便求解）：
- $R_1$: 面粉（Flour）
- $R_2$: 鸡蛋（Egg）
- $R_3$: 黄油（Butter）

## 2. 数学建模

### 变量定义

- **产品件数向量**：
  $$
  \mathbf{x} = \begin{pmatrix} x_1 \\ x_2 \\ x_3 \end{pmatrix} \in \mathbb{R}^3
  $$
  其中 $x_j$ 表示产品 $N_j$ 的生产数量。

- **资源消耗矩阵**：
  $$
  A = \begin{pmatrix}
  a_{11} & a_{12} & a_{13} \\
  a_{21} & a_{22} & a_{23} \\
  a_{31} & a_{32} & a_{33}
  \end{pmatrix} \in \mathbb{R}^{3 \times 3}
  $$
  其中 $a_{ij}$ 表示生产一个单位的产品 $N_j$ 需要的资源 $R_i$ 数量。

- **资源总量向量**：
  $$
  \mathbf{b} = \begin{pmatrix} b_1 \\ b_2 \\ b_3 \end{pmatrix} \in \mathbb{R}^3
  $$
  其中 $b_i$ 表示资源 $R_i$ 的可用总量。

### 线性方程组

如果我们生产 $x_1, x_2, x_3$ 单位的相应产品，资源 $R_i$ 的总消耗为：
$$
a_{i1}x_1 + a_{i2}x_2 + a_{i3}x_3
$$

为了恰好用完所有资源，必须满足：
$$
\begin{cases}
a_{11}x_1 + a_{12}x_2 + a_{13}x_3 & = b_1 \\
a_{21}x_1 + a_{22}x_2 + a_{23}x_3 & = b_2 \\
a_{31}x_1 + a_{32}x_2 + a_{33}x_3 & = b_3
\end{cases}
$$

用矩阵-向量形式可简写为：
$$
A \mathbf{x} = \mathbf{b}
$$

这是一个**线性方程组**，我们需要求解向量 $\mathbf{x}$。

## 3. Python 实现：定义数据

In [4]:
import numpy as np

# 资源消耗矩阵 A（3 种资源 × 3 种产品）
# A[i][j] = a_{i+1,j+1}（生产产品 N_{j+1} 需要资源 R_{i+1} 的量）
A = np.array([
    [0.5, 0.2, 0.4],  # R1: 面粉
    [0.3, 0.1, 0.2],  # R2: 鸡蛋
    [0.2, 0.1, 0.3],  # R3: 黄油
])

# 资源总量向量 b（每种资源的可用总量）
b = np.array([10.0, 6.0, 5.0])

print('资源消耗矩阵 A =')
print(A)
print('\n资源总量向量 b =', b)

资源消耗矩阵 A =
[[0.5 0.2 0.4]
 [0.3 0.1 0.2]
 [0.2 0.1 0.3]]

资源总量向量 b = [10.  6.  5.]


## 4. 求解线性方程组：$A\mathbf{x} = \mathbf{b}$

使用 NumPy 的 `linalg.solve()` 求解线性方程组（当 $A$ 为方阵且可逆时）。

In [5]:
# 求解线性方程组 A @ x = b
try:
    x = np.linalg.solve(A, b)
    print('生产计划 x =')
    print(x)
    print('\n各产品生产数量：')
    print(f'  - 面包（N1）: {x[0]:.2f}')
    print(f'  - 糯米滋（N2）: {x[1]:.2f}')
    print(f'  - 蛋黄酥（N3）: {x[2]:.2f}')
except np.linalg.LinAlgError:
    print('矩阵 A 不可逆，方程组无唯一解')

生产计划 x =
[ 20. -20.  10.]

各产品生产数量：
  - 面包（N1）: 20.00
  - 糯米滋（N2）: -20.00
  - 蛋黄酥（N3）: 10.00


## 5. 验证解的正确性

检查计算出的 $\mathbf{x}$ 是否满足 $A\mathbf{x} = \mathbf{b}$。

In [6]:
# 验证：计算 A @ x 并与 b 比较
if 'x' in locals():
    resource_usage = A @ x
    print('计算得到的资源使用量（A @ x）:')
    print(resource_usage)
    print('\n资源总量 b:')
    print(b)
    print('\n误差（A @ x - b）:')
    print(resource_usage - b)
    print('\n验证通过:', np.allclose(resource_usage, b))

计算得到的资源使用量（A @ x）:
[10.  6.  5.]

资源总量 b:
[10.  6.  5.]

误差（A @ x - b）:
[0. 0. 0.]

验证通过: True


## 6. 矩阵-向量乘法的几何意义

$A\mathbf{x}$ 的计算过程：

$$
A\mathbf{x} = \begin{pmatrix}
a_{11} & a_{12} & a_{13} \\
a_{21} & a_{22} & a_{23} \\
a_{31} & a_{32} & a_{33}
\end{pmatrix}
\begin{pmatrix} x_1 \\ x_2 \\ x_3 \end{pmatrix}
= \begin{pmatrix}
a_{11}x_1 + a_{12}x_2 + a_{13}x_3 \\
a_{21}x_1 + a_{22}x_2 + a_{23}x_3 \\
a_{31}x_1 + a_{32}x_2 + a_{33}x_3
\end{pmatrix}
$$

每一行对应一种资源的总消耗量。

In [7]:
# 手动演示矩阵-向量乘法
if 'x' in locals():
    print('手动计算 A @ x 的每一行：')
    for i in range(3):
        row_result = sum(A[i, j] * x[j] for j in range(3))
        print(f'第 {i+1} 行: {A[i, 0]:.2f}×{x[0]:.2f} + {A[i, 1]:.2f}×{x[1]:.2f} + {A[i, 2]:.2f}×{x[2]:.2f} = {row_result:.2f}')

手动计算 A @ x 的每一行：
第 1 行: 0.50×20.00 + 0.20×-20.00 + 0.40×10.00 = 10.00
第 2 行: 0.30×20.00 + 0.10×-20.00 + 0.20×10.00 = 6.00
第 3 行: 0.20×20.00 + 0.10×-20.00 + 0.30×10.00 = 5.00
